theme: jekyll-theme-minimal
webmaster_verifications:
  yandex: bfcafc040673553f

google_analytics: UA-148372418-3

plugins:
  - jekyll-redirect-from

title: Nicegram
email: nicegram@appvillis.com

twitter_username: nicegramapp
github_username:  nicegram

logo: Icon_tr.png
include: [".well-known"]

redirect_from:
  json: false
